### ISSUE TITLE
Add instructions for running

### ISSUE THREAD

**Issue by JasonStoltz** [wambozi/elastic-webcrawler#10]
For those of us who are less than familiar with Go and Docker, some simple instructions for how to configure and run this would be much appreciated.

**Comment by wambozi** [comment]
Yea that seems fair

**Comment by JasonStoltz** [comment]
FWIW, these are the rough notes from a colleague running this against App Search:

1. Launch App Search and Elasticsearch

2. Create a local config file:
```
elasticsearch:
  endpoint: http://docker.for.mac.localhost:9200
appsearch:
  endpoint: http://docker.for.mac.localhost:3002
  api: /api/as/v1/
  token: private-xxxxxxxxxxxxxxx
server:
  port: 8081
  readHeaderTimeoutMillis: 3000
```

3. Run the docker command:
```
docker run -v "`pwd`:/conf/" -e ENV_ID=local -p8081:8081 -it wambozi/elastic-webcrawler
```

    `-v` : Mount the current dir into /conf dir of the container (so it makes local.yml accessible here)
    `-e`: Required to specify the name of the env file (defaults are buggy and it took me some time to find it)
    `-p` expose the webserver port  

4. Create the engine in app search (swiftype-demo for me)
    If you don’t you will see a lot of 404 into the logs. The engine is not created for you

5. Launch indexing
curl -XPOST localhost:8081/crawl -d '{
    "engine": "swiftype-website",
    "url": "https://swiftype.com/",
    "type": "app-search"
}'
